### ISSUE TITLE
tox warning when running default configuration

### ISSUE THREAD

**Issue by alexcoca** [pyscaffold/dsproject-demo#1]
Hello,

I am testing this as a potential way to structure a project I'm working on. First of all - awesome job. 

I've set up my repository and made a few changes to the environment files and so on and I tested to see that `tox` works with some dummy test file and dummy test function before adding my code to the repository.  When I run the command `tox`, the test passes but I get the following warning:

![image](https://user-images.githubusercontent.com/30216068/115278304-350c2f00-a13d-11eb-85db-1cc0f2c92c62.png)

The way I understand this is that the `extras` field under `[testenv]`  basically means that tox executes `pip install[testing]` since `extras` is bound to testing. Hence, I don't understand exactly what `tox` complains about? Should I go and explicitly add `deps` to `[testenv]` ?

Many thanks for great work, it's a massive help!

**Comment by FlorianWilhelm** [comment]
Hi @alexcoca, thanks for posting this issue. Have you just cloned this repo? You should use [PyScaffold](https://github.com/pyscaffold/pyscaffold) with the [dsproject extension](https://github.com/pyscaffold/pyscaffoldext-dsproject) to set up your project. 

Besides, how did you create a virtual environment? With conda or pip? Please use the issue tracker of [PyScaffold](https://github.com/pyscaffold/pyscaffold) or [dsproject extension](https://github.com/pyscaffold/pyscaffoldext-dsproject). Thank you :-)

**Comment by alexcoca** [comment]
Hi @FlorianWilhelm ,

Apologies for getting the repo wrong. I'll move the repo there since I actually did use the extension to create the project. 

Alex
